# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: hmarr/debug-action@v1.0.0
      - run: echo "Hello there '${{github.event.head_commit.message}}' !"
      - run: echo "Hello wat '${{toJson(github.event.head_commit.message)}}' !"
      - run: echo "Hello user '${{github.event.commits[0].author.username}} !"
        
  # This workflow contains a single job called "build"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    if: (contains(github.event.head_commit.message, 'patch') && contains(github.event.commits.*.author.username, 'Rugvip')) || github.event_name == 'workflow_dispatch'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:      
      - run: echo "Hello there!"
