# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    outputs:
      needs_release: ${{ steps.release_check.outputs.needs_release }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: fetch previous commit
        run: git fetch origin '${{ github.event.before }}'
      - uses: hmarr/debug-action@v1.0.0
      - run: echo "Hello there '${{github.event.head_commit.message}}' !"
      - run: echo "Hello wat '${{toJson(github.event.head_commit.message)}}' !"
      - run: echo "Hello user '${{github.event.commits[0].author.username}} !"
      - name: Check if release
        id: release_check
        run: node check-if-release.js
        env:
          COMMIT_SHA_BEFORE: '${{ github.event.before }}'
        
  # This workflow contains a single job called "build"
  release:
    needs: [build]

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    if: needs.build.outputs.needs_release == 'true'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:      
      - run: echo "Hello there!"
